//
//  ActivityEvent.m
//  LinkMe
//
//  Created by Summer Wu on 14-9-1.
//  Copyright (c) 2014年 Summer.Wu. All rights reserved.
//

#import "ActivityEvent.h"

@implementation ActivityEvent

DEF_NOTIFICATION(LOAD_ACTIVITY_START)
DEF_NOTIFICATION(LOAD_ACTIVITY_SUCCESS)
DEF_NOTIFICATION(LOAD_ACTIVITY_FAILED)

DEF_NOTIFICATION(LOAD_LOCAL_ACTIVITY)

DEF_NOTIFICATION(ADD_ACTIVITY_START)
DEF_NOTIFICATION(ADD_ACTIVITY_SUCCESS)
DEF_NOTIFICATION(ADD_ACTIVITY_FAILED)

@end
