//
//  CommendEvent.h
//  LinkMe
//
//  Created by Summer Wu on 14-11-22.
//  Copyright (c) 2014年 Summer.Wu. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "Bee.h"

@interface CommendEvent : NSObject

AS_NOTIFICATION(LOAD_APP_COMMEND_START)
AS_NOTIFICATION(LOAD_APP_COMMEND_SUCCESS)
AS_NOTIFICATION(LOAD_APP_COMMEND_FAILED)

AS_NOTIFICATION(SEND_INVITE_START)
AS_NOTIFICATION(SEND_INVITE_SUCCESS)
AS_NOTIFICATION(SEND_INVITE_FAILED)

AS_NOTIFICATION(CHECK_INVITE_STATUS_START)
AS_NOTIFICATION(CHECK_INVITE_STATUS_SUCCESS)
AS_NOTIFICATION(CHECK_INVITE_STATUS_FAILED)

AS_NOTIFICATION(CHECK_IS_BE_INVITE_START)
AS_NOTIFICATION(CHECK_IS_BE_INVITE_SUCCESS)
AS_NOTIFICATION(CHECK_IS_BE_INVITE_FAILED)

AS_NOTIFICATION(RECEIVE_INVITE_START)
AS_NOTIFICATION(RECEIVE_INVITE_SUCCESS)
AS_NOTIFICATION(RECEIVE_INVITE_FAILED)

@end
