//
//  CommendEvent.m
//  LinkMe
//
//  Created by Summer Wu on 14-11-22.
//  Copyright (c) 2014年 Summer.Wu. All rights reserved.
//

#import "CommendEvent.h"

@implementation CommendEvent

DEF_NOTIFICATION(LOAD_APP_COMMEND_START)
DEF_NOTIFICATION(LOAD_APP_COMMEND_SUCCESS)
DEF_NOTIFICATION(LOAD_APP_COMMEND_FAILED)

DEF_NOTIFICATION(SEND_INVITE_START)
DEF_NOTIFICATION(SEND_INVITE_SUCCESS)
DEF_NOTIFICATION(SEND_INVITE_FAILED)

DEF_NOTIFICATION(CHECK_INVITE_STATUS_START)
DEF_NOTIFICATION(CHECK_INVITE_STATUS_SUCCESS)
DEF_NOTIFICATION(CHECK_INVITE_STATUS_FAILED)



@end
