//
//  LoginEvent.m
//  LinkMe
//
//  Created by Summer Wu on 14-8-26.
//  Copyright (c) 2014年 Summer.Wu. All rights reserved.
//

#import "UserEvent.h"

@implementation UserEvent

DEF_NOTIFICATION(LOGIN)
DEF_NOTIFICATION(LOGIN_SUCCESS)
DEF_NOTIFICATION(LOGIN_FAILED)
DEF_NOTIFICATION(LOGIN_FAILED_USER_NOT_EXISTED)
DEF_NOTIFICATION(LOGIN_FAILED_PASS_ERROR)


DEF_NOTIFICATION(REGISTER)
DEF_NOTIFICATION(REGISTER_SUCCESS)
DEF_NOTIFICATION(REGISTER_FAILED)
DEF_NOTIFICATION(REGISTER_FAILED_EXISTED)
DEF_NOTIFICATION(REGISTER_FAILED_INFO_ERROR)

DEF_NOTIFICATION(USER_NOT_FOUND)

@end
